import { JourneyOption, StationHeatmapPoint, TimelineStep } from './types';

export const JOURNEY_OPTIONS: JourneyOption[] = [
  {
    id: 'direct-cab',
    type: 'cab',
    title: 'Direct Cab',
    icons: ['🚕'],
    subtitle: 'Door to door, no transfers',
    price: 919,
    time: 52,
    badge: 'Surge Pricing Active 1.8x',
    badgeColor: 'red',
  },
  {
    id: 'direct-auto',
    type: 'auto',
    title: 'Direct Auto',
    icons: ['🛺'],
    subtitle: 'Door to door, no transfers',
    price: 556,
    time: 48,
    badge: 'High Wait Time ~25 mins',
    badgeColor: 'orange',
  },
  {
    id: 'direct-bike',
    type: 'bike',
    title: 'Direct Bike',
    icons: ['🏍'],
    subtitle: 'Door to door, no transfers',
    price: 398,
    time: 44,
  },
  {
    id: 'cab-metro',
    type: 'cab-metro',
    title: 'Cab + Metro',
    icons: ['🚕', '🚇'],
    subtitle: 'Rapid transit with private first/last mile',
    price: 450,
    time: 38,
    breakdown: '₹200 cab · ₹70 metro · ₹180 cab',
    badge: 'Save ₹469 vs direct cab',
    badgeColor: 'teal',
  },
  {
    id: 'auto-metro',
    type: 'auto-metro',
    title: 'Auto + Metro',
    icons: ['🛺', '🚇'],
    subtitle: 'Economical multi-modal crossing',
    price: 220,
    time: 32,
    breakdown: '₹80 auto · ₹70 metro · ₹70 auto',
    badge: 'Save ₹336 vs direct cab',
    badgeColor: 'teal',
  },
  {
    id: 'bike-metro',
    type: 'bike-metro',
    title: 'Bike + Metro',
    icons: ['🚲', '🚇'],
    subtitle: 'Speedy bike feeder link & rapid transit combination',
    price: 150,
    time: 28,
    breakdown: '₹50 bike · ₹70 metro · ₹30 bike',
    badge: '⭐ Recommended — Fastest & Cheapest',
    badgeColor: 'gold-mint',
    secondBadge: 'Both legs pre-booked. Driver waiting at metro exit.',
    isHero: true,
  },
];

export const TIMELINE_STEPS: TimelineStep[] = [
  {
    id: 1,
    title: 'Bike arriving at IIM Mumbai, Powai',
    subtitle: 'Driver Rajan S. · 3 mins away · KA 05 BK 2341',
    statusText: 'En route to you',
    completed: false,
    active: true,
    type: 'pickup',
  },
  {
    id: 2,
    title: 'Metro — Aarey JVLR Metro Station',
    subtitle: 'Western Line · Platform 2 · Departs 3:11 PM',
    statusText: 'Ticket auto-booked · Seat reserved',
    completed: false,
    active: false,
    type: 'metro',
  },
  {
    id: 3,
    title: 'Arrive Churchgate Metro Station — 3:26 PM',
    subtitle: 'Exit Gate 1 · Your ride will be waiting',
    statusText: 'Auto-synchronized schedule',
    completed: false,
    active: false,
    type: 'arrival',
  },
  {
    id: 4,
    title: 'Last ride to Rameshwaram Cafe, Churchgate',
    subtitle: 'Driver Priya M. already positioned · 0 wait time',
    statusText: 'Pre-committed · Will not cancel',
    completed: false,
    active: false,
    type: 'dropoff',
  },
];

export const HEATMAP_POINTS: StationHeatmapPoint[] = [
  {
    id: 'churchgate',
    name: 'Churchgate Metro',
    passengers: 32,
    time: '3:26 PM',
    color: 'gold',
    x: 28,
    y: 78,
    size: 70,
  },
  {
    id: 'cst',
    name: 'CST Station',
    passengers: 24,
    time: '3:22 PM',
    color: 'teal',
    x: 48,
    y: 65,
    size: 55,
  },
  {
    id: 'nariman',
    name: 'Nariman Point',
    passengers: 18,
    time: '3:34 PM',
    color: 'teal',
    x: 22,
    y: 88,
    size: 45,
  },
  {
    id: 'bandra',
    name: 'Bandra Station',
    passengers: 12,
    time: '3:45 PM',
    color: 'teal',
    x: 35,
    y: 42,
    size: 35,
  },
  {
    id: 'andheri',
    name: 'Andheri Metro',
    passengers: 9,
    time: '4:05 PM',
    color: 'teal',
    x: 42,
    y: 24,
    size: 30,
  },
  {
    id: 'dadar',
    name: 'Dadar Central',
    passengers: 7,
    time: '3:38 PM',
    color: 'teal',
    x: 55,
    y: 50,
    size: 28,
  },
];
